export const MAP_CONFIG = {
  TILE_SIZE: 32, 
  COLS: 15,      
  ROWS: 13,      
};

export const TILE = {
  FLOOR:   0, 
  WALL:    1, 
  MACHINE: 2, 
  DECOR:   3, 
  PORTAL:  4, 
  WARP:    5, 
};

export const DIFFICULTY_CONFIG = {
  easy: {
    key: 'easy', label: 'FÁCIL', icon: ':)',
    lives: 3,         
    quizTime: 45,     
    scoreBonus: 100,  
    color: '#50e878', colorDark: '#1a5a2a', 
  },
  medium: {
    key: 'medium', label: 'MÉDIO', icon: ':|',
    lives: 2, quizTime: 25, scoreBonus: 200,
    color: '#ffde00', colorDark: '#5a4a00',
  },
  hard: {
    key: 'hard', label: 'DIFÍCIL', icon: '>:(',
    lives: 1, quizTime: 15, scoreBonus: 350,
    color: '#ff5050', colorDark: '#5a0a0a',
  },
};

export const STORY = {
  intro: [
    { speaker: 'NARRADOR',    portrait: 'narrator', text: 'Era um sábado ensolarado quando Lucas recebeu uma mensagem do avô...' },
    { speaker: 'AVÔ AUGUSTO', portrait: 'grandpa',  text: '"Lucas! Venha rápido para a garagem. Tenho algo incrível para te mostrar!"' },
    { speaker: 'NARRADOR',    portrait: 'narrator', text: 'Lucas pedalou até a casa do avô e entrou pela porta dos fundos...' },
    { speaker: 'LUCAS',       portrait: 'lucas',    text: '"Vô? O que é essa máquina enorme? Ela parece antiga e futurista ao mesmo tempo!"' },
    { speaker: 'AVÔ AUGUSTO', portrait: 'grandpa',  text: '"É a minha MÁQUINA DO TEMPO, meu neto! Levei 40 anos construindo..."' },
    { speaker: 'AVÔ AUGUSTO', portrait: 'grandpa',  text: '"...mas ela parou de funcionar. O núcleo de processamento quebrou em 5 pontos históricos!"' },
    { speaker: 'AVÔ AUGUSTO', portrait: 'grandpa',  text: '"Para consertá-la, precisamos viajar para as épocas onde os maiores computadores da história foram criados..."' },
    { speaker: 'AVÔ AUGUSTO', portrait: 'grandpa',  text: '"...e absorver o conhecimento deles. Cada pergunta respondida certa repara 20% do núcleo!"' },
    { speaker: 'LUCAS',       portrait: 'lucas',    text: '"Mas vô... eu não sei nada sobre computadores antigos!"' },
    { speaker: 'AVÔ AUGUSTO', portrait: 'grandpa',  text: '"É por isso que eu estarei aqui te guiando por rádio! Vamos lá, aventureiro!"' },
  ],
};

export const ERAS = [
  {
    id: 'garage',
    name: 'GARAGEM DO AVÔ',
    year: '2024',
    icon: '🔧',
    bgColor: '#1a120a', floorColor: '#3d2e1a',
    wallColor: '#1e1408', accentColor: '#e08020',
    decorType: 'workbench',
    machine: null, 
    introMsg: [{
      speaker: 'AVÔ AUGUSTO', portrait: 'grandpa',
      text: 'Bem-vindo à minha garagem, Lucas! Aqui está a Máquina do Tempo. Ela está com o núcleo quebrado. O portal azul ao fundo nos levará ao passado — chegue até ele e pressione E para iniciarmos a jornada!',
    }],
    map: [
      [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
      [1,3,3,0,0,3,0,0,0,3,0,0,3,3,1],
      [1,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
      [1,0,0,3,0,0,0,0,0,0,0,3,0,0,1],
      [1,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
      [1,3,0,0,0,0,0,0,0,0,0,0,0,3,1],
      [1,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
      [1,3,0,0,0,0,0,0,0,0,0,0,0,3,1],
      [1,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
      [1,0,0,3,0,0,0,0,0,0,0,3,0,0,1],
      [1,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
      [1,3,3,0,0,0,0,5,0,0,0,0,3,3,1], 
      [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
    ],
    playerStart: { col: 7, row: 5 },  
    portalPos:   { col: 7, row: 11 }, 
    machinePos:  null,                
  },
  {
    id: 'era_eniac',
    name: 'LAB. BALLISTIC / ENIAC',
    year: '1945',
    icon: '⚙️',
    bgColor: '#080c06', floorColor: '#1a1c12',
    wallColor: '#0c100a', accentColor: '#c8a820',
    decorType: 'military',
    introMsg: [{
      speaker: 'AVÔ AUGUSTO', portrait: 'grandpa',
      text: 'Incrível! Estamos em Filadélfia, 1945! Este é o Moore School of Electrical Engineering. A 2ª Guerra está nos últimos meses e cientistas trabalham dia e noite neste ENIAC — o gigante eletrônico. Encontre-o e responda a pergunta!',
    }],
    machine: {
      id: 'eniac',
      name: 'ENIAC (1945)',
      portraitColor: '#6a4200', 
      tileColor: '#c07800',     
      description: 'ENIAC — Electronic Numerical Integrator And Computer. Pesava 30 toneladas, ocupava 167m² e usava 18.000 válvulas termoiônicas. Era 1.000× mais rápido que qualquer calculadora da época!',
      questionsByDifficulty: {
        easy: {
          question: 'O ENIAC foi programado por um grupo de mulheres que ficaram famosas. Qual era o apelido dessas programadoras?',
          options: ['ENIAC Girls', 'Tech Ladies', 'Code Queens', 'Binary Sisters'],
          correctIndex: 0, 
          curiosity: ' As "ENIAC Girls" — Jean Jennings, Frances Bilas, Betty Jean Jennings, Ruth Lichterman, Marlyn Wescoff e Frances Elizabeth Holberton — aprenderam a programar o ENIAC sem qualquer manual, pois tudo era secreto. Suas contribuições foram ignoradas por décadas!',
        },
        medium: {
          question: 'Para que o ENIAC foi originalmente construído durante a 2ª Guerra Mundial?',
          options: ['Prever o clima', 'Calcular tabelas de artilharia', 'Controlar aviões', 'Cifrar mensagens secretas'],
          correctIndex: 1,
          curiosity: ' O ENIAC calculava trajetórias de artilharia em segundos — tarefa que levava dias a humanos. Seu primeiro grande teste foi calcular a viabilidade da bomba de hidrogênio em 1949. Programado por 6 mulheres conhecidas como as "ENIAC Girls"!',
        },
        hard: {
          question: 'O ENIAC usava 18.000 válvulas e tinha uma limitação crítica de confiabilidade. Qual era e como foi parcialmente resolvida?',
          options: [
            'Superaquecia a cada 10 min; solução: refrigeração a água',
            'Válvulas queimavam com alta frequência; solução: mantê-las sempre ligadas para estabilizar temperatura',
            'Perdia dados ao desligar; solução: cartões perfurados para backup',
            'Consumia energia demais; solução: operação noturna com tarifa reduzida',
          ],
          correctIndex: 1,
          curiosity: ' O ENIAC falhava em média a cada 5–10 horas devido a válvulas queimadas. A solução contraintuitiva foi nunca desligá-lo — as válvulas eram mais estáveis a temperatura constante. O consumo era de 150kW, o equivalente a 150 chuveiros elétricos ligados simultaneamente!',
        },
      },
    },
    map: [
      [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
      [1,0,0,1,0,0,0,0,0,0,0,1,0,0,1],
      [1,3,0,0,0,3,0,0,0,3,0,0,0,3,1],
      [1,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
      [1,1,1,0,0,0,0,0,0,0,0,0,1,1,1],
      [1,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
      [1,0,2,0,0,0,0,0,0,0,3,0,0,0,1], 
      [1,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
      [1,1,1,0,0,0,0,0,0,0,0,0,1,1,1],
      [1,0,0,0,0,3,0,0,0,3,0,0,0,0,1],
      [1,3,0,0,0,0,0,0,0,0,0,0,0,3,1],
      [1,0,0,0,0,0,0,0,5,0,0,0,0,0,1],
      [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
    ],
    playerStart: { col: 7, row: 10 },
    machinePos:  { col: 2, row: 6 },  
    portalPos:   { col: 8, row: 11 }, 
  },
  {
    id: 'era_apple2',
    name: 'GARAGEM — SILICON VALLEY',
    year: '1977',
    icon: '🍎',
    bgColor: '#0a0f14', floorColor: '#1a2822',
    wallColor: '#0e1a14', accentColor: '#44dd66',
    decorType: 'garage_sv',
    introMsg: [{
      speaker: 'AVÔ AUGUSTO', portrait: 'grandpa',
      text: 'Estamos em Los Altos, Califórnia — 1977! Esta é a garagem dos Jobs. Dois Steves estão construindo o futuro aqui. O Apple II está sobre a bancada central. Chegue até ele e responda!',
    }],
    machine: {
      id: 'apple2',
      name: 'APPLE II (1977)',
      portraitColor: '#1a5020',
      tileColor: '#33bb55',
      description: 'O Apple II foi projetado por Steve Wozniak e foi um dos primeiros microcomputadores pessoais de sucesso comercial. Gráficos coloridos, BASIC embutido, slots de expansão — abriu a computação para pessoas comuns!',
      questionsByDifficulty: {
        easy: {
          question: 'Em qual estado americano Steve Wozniak e Steve Jobs desenvolveram o Apple II numa garagem?',
          options: ['Texas', 'Nova York', 'Califórnia', 'Washington'],
          correctIndex: 2,
          curiosity: ' A garagem de Los Altos, Califórnia, é considerada o berço do Vale do Silício. Steve Jobs vendeu sua kombi VW e Wozniak sua calculadora HP para financiar o Apple I. A Apple foi fundada em 1976 com capital inicial de apenas US$ 1.300!',
        },
        medium: {
          question: 'Steve Wozniak projetou o Apple II para ser acessível a todos. Qual recurso o tornou revolucionário?',
          options: ['Primeiro com Wi-Fi', 'Memória de 1 TB', 'Gráficos coloridos e BASIC embutido', 'Tela sensível ao toque'],
          correctIndex: 2,
          curiosity: ' O Apple II vendeu mais de 5 milhões de unidades! A planilha VisiCalc foi lançada nele, transformando o PC numa ferramenta de negócios real. Steve Jobs levantou US$250.000 mostrando o protótipo para investidores numa garagem!',
        },
        hard: {
          question: 'Qual software lançado exclusivamente para o Apple II em 1979 foi fundamental para sua adoção por empresas, transformando o PC numa ferramenta de negócios?',
          options: [
            'WordStar — processador de texto pioneiro',
            'VisiCalc — primeira planilha eletrônica comercial',
            'dBASE II — banco de dados relacional',
            'CP/M — sistema operacional de disco',
          ],
          correctIndex: 1,
          curiosity: ' O VisiCalc (Visible Calculator) foi desenvolvido por Dan Bricklin e Bob Frankston em 1979. Empresas compravam Apple IIs especificamente para rodar o VisiCalc — um fenômeno chamado de "aplicativo matador" (killer app). O VisiCalc sozinho vendeu mais de 700.000 cópias!',
        },
      },
    },
    map: [
      [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
      [1,3,3,3,0,0,0,0,0,0,0,3,3,3,1],
      [1,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
      [1,3,0,0,0,0,0,0,0,0,0,0,0,3,1],
      [1,0,0,0,0,1,1,0,1,1,0,0,0,0,1],
      [1,3,0,0,0,0,0,0,0,0,0,0,0,3,1],
      [1,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
      [1,0,0,0,0,0,0,2,0,0,0,0,0,0,1],
      [1,3,0,0,0,0,0,0,0,0,0,0,0,3,1],
      [1,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
      [1,3,3,0,0,0,0,0,0,0,0,0,3,3,1],
      [1,0,0,0,0,5,0,0,0,0,0,0,0,0,1],
      [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
    ],
    playerStart: { col: 7, row: 2 },
    machinePos:  { col: 7, row: 7 },
    portalPos:   { col: 5, row: 11 },
  },
  {
    id: 'era_ibmpc',
    name: 'ESCRITÓRIO IBM — BOCA RATON',
    year: '1981',
    icon: '🖥️',
    bgColor: '#060810', floorColor: '#1c1e30',
    wallColor: '#0c0e1e', accentColor: '#4488ff',
    decorType: 'corporate',
    introMsg: [{
      speaker: 'AVÔ AUGUSTO', portrait: 'grandpa',
      text: 'Boca Raton, Flórida — 1981! Este escritório da IBM acaba de receber o novo PC 5150. Os engenheiros criaram este computador em tempo recorde — apenas 1 ano! Encontre o IBM PC e aprenda sobre o sistema que dominou décadas!',
    }],
    machine: {
      id: 'ibmpc',
      name: 'IBM PC 5150 (1981)',
      portraitColor: '#10184a',
      tileColor: '#2244cc',
      description: 'O IBM PC 5150 padronizou a arquitetura dos computadores pessoais para sempre. Rodava o MS-DOS da Microsoft e criou o padrão "IBM-compatible" — praticamente todo PC hoje ainda usa derivados dessa arquitetura!',
      questionsByDifficulty: {
        easy: {
          question: 'Qual empresa famosa forneceu o sistema operacional para o IBM PC 5150, tornando-se uma das maiores do mundo?',
          options: ['Apple', 'Microsoft', 'Google', 'Intel'],
          correctIndex: 1,
          curiosity: ' Bill Gates tinha apenas 25 anos quando a Microsoft assinou o contrato com a IBM in 1980. A Microsoft nem tinha um sistema operacional na época — Gates comprou o QDOS de uma empresa por US$ 50.000 e o adaptou para se tornar o MS-DOS. Esse foi o negócio do século!',
        },
        medium: {
          question: 'O IBM PC 5150 usou um sistema operacional que dominaria por décadas. Qual era?',
          options: ['UNIX', 'CP/M', 'MS-DOS', 'Apple DOS'],
          correctIndex: 2,
          curiosity: ' A Microsoft licenciou o MS-DOS da IBM mas manteve os direitos de vender para outros — decisão que transformou Bill Gates no homem mais rico do mundo nos anos 90! IBM queria apenas um bom produto; Gates queria dominar o mercado.',
        },
        hard: {
          question: 'Por que a decisão da Microsoft de manter os direitos de licenciamento do MS-DOS foi historicamente mais importante do que o próprio IBM PC?',
          options: [
            'Permitiu vender o SO a todos os fabricantes de clones IBM-compatible, criando um monopólio de software',
            'Forçou a IBM a usar processadores Intel exclusivamente, enriquecendo a Intel',
            'Impediu que a Apple lançasse um sistema operacional compatível com o PC',
            'Gerou royalties suficientes para a Microsoft financiar o Windows sem investidores',
          ],
          correctIndex: 0,
          curiosity: ' A IBM cometeu o erro estratégico de não exigir exclusividade do MS-DOS. Quando os "clones IBM-compatible" explodiram no mercado (Compaq, HP, Dell...), todos precisavam de MS-DOS — pagando royalties à Microsoft, não à IBM. Em 10 anos, a Microsoft valia mais que a IBM!',
        },
      },
    },
    map: [
      [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
      [1,0,0,1,0,0,0,0,0,0,0,1,0,0,1],
      [1,0,0,0,0,3,0,0,0,3,0,0,0,0,1],
      [1,1,0,0,0,0,0,0,0,0,0,0,0,1,1],
      [1,0,0,3,0,0,0,0,0,0,0,3,0,0,1],
      [1,0,0,0,0,2,0,0,0,0,0,0,0,0,1],
      [1,1,0,0,0,0,0,0,0,0,0,0,0,1,1],
      [1,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
      [1,0,0,3,0,0,0,0,0,0,0,3,0,0,1],
      [1,1,0,0,0,0,0,0,0,0,0,0,0,1,1],
      [1,0,0,0,0,3,0,0,0,3,0,0,0,0,1],
      [1,0,0,0,0,0,0,0,0,5,0,0,0,0,1],
      [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
    ],
    playerStart: { col: 2, row: 9 },
    machinePos:  { col: 5, row: 5 },
    portalPos:   { col: 9, row: 11 },
  },
  {
    id: 'era_mac',
    name: 'TEATRO — LANÇAMENTO MAC 1984',
    year: '1984',
    icon: '🖱️',
    bgColor: '#100808', floorColor: '#261414',
    wallColor: '#160a0a', accentColor: '#ff5555',
    decorType: 'theater',
    introMsg: [{
      speaker: 'AVÔ AUGUSTO', portrait: 'grandpa',
      text: '24 de Janeiro de 1984 — o dia que mudou a informática! Steve Jobs está prestes a apresentar o Macintosh neste teatro. O Mac está no palco. Avance até ele e responda — estamos na história!',
    }],
    machine: {
      id: 'mac128',
      name: 'MACINTOSH 128K (1984)',
      portraitColor: '#4a1010',
      tileColor: '#cc2233',
      description: 'O Macintosh original foi o primeiro PC de sucesso com interface gráfica (GUI) e mouse. Steve Jobs disse: "Olá. Eu sou o Macintosh" — e o computador falou sozinho! O comercial "1984" ainda é lendário.',
      questionsByDifficulty: {
        easy: {
          question: 'O famoso comercial "1984" do Macintosh foi exibido durante qual evento esportivo americano, visto por milhões de pessoas?',
          options: ['Copa do Mundo FIFA', 'Super Bowl XVIII', 'Olimpíadas de Los Angeles', 'NBA Finals 1984'],
          correctIndex: 1,
          curiosity: ' O comercial "1984" foi ao ar em 22 de janeiro de 1984 durante o Super Bowl XVIII, assistido por 77 milhões de americanos. Dirigido por Ridley Scott (de Blade Runner), custou US$ 1,5 milhão e foi exibido apenas uma vez na TV — se tornando um dos maiores comerciais da história!',
        },
        medium: {
          question: 'O Macintosh 128K popularizou algo que usamos em todo PC até hoje. O que foi?',
          options: ['Teclado mecânico RGB', 'Interface gráfica com mouse', 'Disco rígido interno de 1GB', 'Conexão com a internet'],
          correctIndex: 1,
          curiosity: ' O famoso comercial "1984" foi dirigido por Ridley Scott e custou US$1,5 milhão — exibido apenas uma vez no Super Bowl. O Macintosh original custava US$2.495 (≈ US$7.500 hoje). A interface gráfica foi "inspirada" no trabalho da Xerox PARC!',
        },
        hard: {
          question: 'A interface gráfica do Macintosh original foi fortemente inspirada em pesquisa que a Apple viu numa visita a outra empresa. De onde veio essa inspiração?',
          options: [
            'Do sistema operacional UNIX do Bell Labs da AT&T',
            'Do Xerox Alto desenvolvido no Xerox PARC em 1973',
            'Do sistema Atari ST lançado simultaneamente em 1984',
            'Do projeto LISA da própria Apple, abandonado em 1983',
          ],
          correctIndex: 1,
          curiosity: ' Em 1979, Steve Jobs visitou o Xerox PARC e ficou maravilhado com o Xerox Alto — que tinha GUI, mouse e janelas desde 1973! A Xerox não sabia o que fazer com a invenção; Jobs soube. Bill Gates depois "inspirou-se" no Mac para criar o Windows. Como Jobs disse: "Nós todos copiamos da Xerox."',
        },
      },
    },
    map: [
      [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
      [1,3,3,3,3,3,0,0,0,3,3,3,3,3,1],
      [1,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
      [1,1,1,1,0,0,0,0,0,0,0,1,1,1,1],
      [1,0,0,0,0,0,0,2,0,0,0,0,0,0,1],
      [1,1,1,1,0,0,0,0,0,0,0,1,1,1,1],
      [1,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
      [1,3,0,3,0,0,0,0,0,0,0,3,0,3,1],
      [1,3,0,3,0,0,0,0,0,0,0,3,0,3,1],
      [1,3,0,3,0,0,0,0,0,0,0,3,0,3,1],
      [1,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
      [1,0,5,0,0,0,0,0,0,0,0,0,0,0,1],
      [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
    ],
    playerStart: { col: 7, row: 10 },
    machinePos:  { col: 7, row: 4 },
    portalPos:   { col: 2, row: 11 },
  },
  {
    id: 'era_modern',
    name: 'DATA CENTER — 2000s',
    year: '2000s',
    icon: '💻',
    bgColor: '#020c14', floorColor: '#0a1822',
    wallColor: '#040e18', accentColor: '#00eeff',
    decorType: 'datacenter',
    introMsg: [{
      speaker: 'AVÔ AUGUSTO', portrait: 'grandpa',
      text: 'A última era! Anos 2000 — processadores multinúcleo, SSDs, internet em todo lugar. Este data center concentra o poder computacional de toda uma geração. É a última peça! Você consegue, Lucas — vamos consertar a máquina do tempo!',
    }],
    machine: {
      id: 'modern_pc',
      name: 'PC MODERNO (2000s)',
      portraitColor: '#031828',
      tileColor: '#0088cc',
      description: 'O PC moderno consolidou décadas de evolução. Processadores multinúcleo, DDR RAM, SSDs NVMe e GPUs dedicadas. Um smartphone de 2024 tem mais poder que todos os computadores do Apollo Program combinados!',
      questionsByDifficulty: {
        easy: {
          question: 'O que significa a sigla SSD, o componente que substituiu o HD mecânico nos computadores modernos?',
          options: ['Super Speed Disk', 'Solid State Drive', 'System Storage Device', 'Serial Speed Data'],
          correctIndex: 1,
          curiosity: ' SSD significa "Solid State Drive" — unidade de estado sólido. Diferente dos HDs tradicionais que usam pratos magnéticos giratórios, os SSDs usam memória flash (como um pen drive gigante). Sem partes móveis, são muito mais rápidos, silenciosos e resistentes a quedas!',
        },
        medium: {
          question: 'O que revolucionou a velocidade de armazenamento dos PCs modernos em comparação com HDs tradicionais?',
          options: ['Mais memória RAM', 'Processador mais rápido', 'SSD (Solid State Drive)', 'Fonte de alimentação melhor'],
          correctIndex: 2,
          curiosity: ' Um SSD NVMe moderno lê a 7.000 MB/s — 100× mais rápido que um HD mecânico dos anos 2000. Os transistores de um CPU moderno são menores que um vírus! O Intel i9 de 2024 tem 24 núcleos e bilhões de transistores a 1nm.',
        },
        hard: {
          question: 'Um SSD NVMe moderno usa a interface PCIe em vez de SATA. Qual é a velocidade de leitura aproximada de um SSD NVMe Gen4 comparado a um HD mecânico padrão de 7200 RPM?',
          options: [
            '2× mais rápido — 300 MB/s vs 150 MB/s',
            '10× mais rápido — 1.500 MB/s vs 150 MB/s',
            '46× mais rápido — 7.000 MB/s vs 150 MB/s',
            '200× mais rápido — 30.000 MB/s vs 150 MB/s',
          ],
          correctIndex: 2,
          curiosity: ' Um HD mecânico de 7200 RPM lê em média 150 MB/s; um SSD NVMe Gen4 como o Samsung 990 Pro lê até 7.450 MB/s — cerca de 46× mais rápido. A latência do SSD é ~0,1ms contra ~10ms do HD (100× menor). O gargalo dos PCs modernos não é mais o armazenamento, mas a largura de banda de memória!',
        },
      },
    },
    map: [
      [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
      [1,3,3,0,3,3,0,0,0,3,3,0,3,3,1],
      [1,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
      [1,3,3,0,3,3,0,0,0,3,3,0,3,3,1],
      [1,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
      [1,0,0,0,0,0,0,2,0,0,0,0,0,0,1],
      [1,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
      [1,3,3,0,3,3,0,0,0,3,3,0,3,3,1],
      [1,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
      [1,3,3,0,3,3,0,0,0,3,3,0,3,3,1],
      [1,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
      [1,0,0,0,0,0,0,5,0,0,0,0,0,0,1],
      [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
    ],
    playerStart: { col: 7, row: 9 },
    machinePos:  { col: 7, row: 5 },
    portalPos:   { col: 7, row: 11 },
  },
];